name: Verify Examples

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - name: Run examples
        run: |
          # Temporarily modify requires in examples to use local build instead of npm package
          for file in examples/*.js; do
            sed -i 's|require(.@uor-foundation/math-js.)|require("../dist")|g' "$file"
            # Also fix cases where files import directly from src instead of dist
            sed -i 's|require(.../src/|require("../dist/|g' "$file"
          done
          
          # Fix custom-base-example.js which has a mix of imports
          sed -i 's|require(.../src/config.)|require("../dist/config")|g' examples/custom-base-example.js
          
          # Run each example in a loop, continuing even if one fails
          for file in examples/*.js; do
            echo "Running $file"
            node "$file" || echo "Example $file failed, continuing..."
          done
