name: Verify Examples

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - name: Run examples
        run: |
          # Temporarily modify requires in examples to use local src instead of npm package
          for file in examples/*.js; do
            sed -i 's|require(.@uor-foundation/math-js.)|require("../dist")|g' "$file"
          done
          
          # Run the examples
          for file in examples/*.js; do
            echo "Running $file"
            node "$file"
          done
